import type { Restaurant } from "@/generated/prisma/client";
import type { CoreFormData } from "@/components/admin/CoreEditorForm";
import type { Lang } from "@/lib/i18n";
import { normalizeFooterVisibility, normalizeWeeklyHours } from "@/lib/restaurant-footer";

function workingHoursText(value: unknown, field = "display"): string {
  if (!value || typeof value !== "object" || Array.isArray(value)) return "";
  const display = (value as Record<string, unknown>)[field];
  return typeof display === "string" ? display : "";
}

export function restaurantToCoreFormData(r: Restaurant): CoreFormData {
  return {
    id: r.id,
    businessName: r.businessName,
    slug: r.slug,
    businessType: r.businessType ?? "",
    templateType: r.templateType,
    categoryNavigationStyle: r.categoryNavigationStyle,
    defaultLang: r.defaultLang as Lang,
    enabledLangs: r.enabledLangs as Lang[],
    logo: r.logo ?? "",
    coverImage: r.coverImage ?? "",
    splashImage: r.splashImage ?? "",
    splashEnabled: r.splashEnabled,
    publicHostname: r.publicHostname ?? "",
    slogan: r.slogan ?? "",
    sloganEn: r.sloganEn ?? "",
    sloganAr: r.sloganAr ?? "",
    sloganRu: r.sloganRu ?? "",
    establishedYear: r.establishedYear,
    currencyCode: r.currencyCode,
    phone: r.phone ?? "",
    email: r.email ?? "",
    whatsappNumber: r.whatsappNumber ?? "",
    websiteUrl: r.websiteUrl ?? "",
    address: r.address ?? "",
    city: r.city ?? "",
    district: r.district ?? "",
    workingHours: workingHoursText(r.workingHours),
    workingHoursEn: workingHoursText(r.workingHours, "displayEn"),
    workingHoursAr: workingHoursText(r.workingHours, "displayAr"),
    workingHoursRu: workingHoursText(r.workingHours, "displayRu"),
    timezone: r.timezone,
    weeklyHours: normalizeWeeklyHours(r.workingHours, r.timezone).schedule,
    instagramUrl: r.instagramUrl ?? "",
    facebookUrl: r.facebookUrl ?? "",
    tiktokUrl: r.tiktokUrl ?? "",
    xUrl: r.xUrl ?? "",
    youtubeUrl: r.youtubeUrl ?? "",
    googleMapsUrl: r.googleMapsUrl ?? "",
    googleReviewsUrl: r.googleReviewsUrl ?? "",
    kdvNotice: r.kdvNotice ?? "",
    kdvNoticeEn: r.kdvNoticeEn ?? "",
    kdvNoticeAr: r.kdvNoticeAr ?? "",
    kdvNoticeRu: r.kdvNoticeRu ?? "",
    allergenNotice: r.allergenNotice ?? "",
    allergenNoticeEn: r.allergenNoticeEn ?? "",
    allergenNoticeAr: r.allergenNoticeAr ?? "",
    allergenNoticeRu: r.allergenNoticeRu ?? "",
    nutritionNotice: r.nutritionNotice ?? "",
    nutritionNoticeEn: r.nutritionNoticeEn ?? "",
    nutritionNoticeAr: r.nutritionNoticeAr ?? "",
    nutritionNoticeRu: r.nutritionNoticeRu ?? "",
    footerDescription: r.footerDescription ?? "",
    footerDescriptionEn: r.footerDescriptionEn ?? "",
    footerDescriptionAr: r.footerDescriptionAr ?? "",
    footerDescriptionRu: r.footerDescriptionRu ?? "",
    footerCopyright: r.footerCopyright ?? "",
    footerVisibility: normalizeFooterVisibility(r.footerVisibility),
    lastPriceChangeAt: r.lastPriceChangeAt?.toISOString().slice(0, 10) ?? "",
    attributionText: r.attributionText ?? "",
    attributionUrl: r.attributionUrl ?? "",
    themeAccent: r.themeAccent ?? "",
    themePrimary: r.themePrimary ?? "",
    themeSecondary: r.themeSecondary ?? "",
    themeBackground: r.themeBackground ?? "",
    themeBorder: r.themeBorder ?? "",
    themeText: r.themeText ?? "",
  };
}
