import type { Restaurant } from "@/generated/prisma/client";
import type { CoreFormData } from "@/components/admin/CoreEditorForm";
import type { Lang } from "@/lib/i18n";
import { normalizeFooterVisibility, normalizeWeeklyHours } from "@/lib/restaurant-footer";

function workingHoursText(value: unknown, field = "display"): string {
  if (!value || typeof value !== "object" || Array.isArray(value)) return "";
  const display = (value as Record<string, unknown>)[field];
  return typeof display === "string" ? display : "";
}

export function restaurantToCoreFormData(r: Restaurant): CoreFormData {
  return {
    id: r.id,
    businessName: r.businessName,
    slug: r.slug,
    businessType: r.businessType ?? "",
    templateType: r.templateType,
    categoryNavigationStyle: r.categoryNavigationStyle,
    defaultLang: r.defaultLang as Lang,
    enabledLangs: r.enabledLangs as Lang[],
    logo: r.logo ?? "",
    coverImage: r.coverImage ?? "",
    splashImage: r.splashImage ?? "",
    splashEnabled: r.splashEnabled,
    publicHostname: r.publicHostname ?? "",
    slogan: r.slogan ?? "",
    sloganEn: r.sloganEn ?? "",
    sloganAr: r.sloganAr ?? "",
    sloganRu: r.sloganRu ?? "",
    sloganDe: r.sloganDe ?? "", sloganFr: r.sloganFr ?? "", sloganEs: r.sloganEs ?? "",
    sloganIt: r.sloganIt ?? "", sloganPl: r.sloganPl ?? "", sloganZh: r.sloganZh ?? "",
    establishedYear: r.establishedYear,
    currencyCode: r.currencyCode,
    phone: r.phone ?? "",
    email: r.email ?? "",
    whatsappNumber: r.whatsappNumber ?? "",
    websiteUrl: r.websiteUrl ?? "",
    address: r.address ?? "",
    city: r.city ?? "",
    district: r.district ?? "",
    workingHours: workingHoursText(r.workingHours),
    workingHoursEn: workingHoursText(r.workingHours, "displayEn"),
    workingHoursAr: workingHoursText(r.workingHours, "displayAr"),
    workingHoursRu: workingHoursText(r.workingHours, "displayRu"),
    workingHoursDe: workingHoursText(r.workingHours, "displayDe"),
    workingHoursFr: workingHoursText(r.workingHours, "displayFr"),
    workingHoursEs: workingHoursText(r.workingHours, "displayEs"),
    workingHoursIt: workingHoursText(r.workingHours, "displayIt"),
    workingHoursPl: workingHoursText(r.workingHours, "displayPl"),
    workingHoursZh: workingHoursText(r.workingHours, "displayZh"),
    timezone: r.timezone,
    weeklyHours: normalizeWeeklyHours(r.workingHours, r.timezone).schedule,
    instagramUrl: r.instagramUrl ?? "",
    facebookUrl: r.facebookUrl ?? "",
    tiktokUrl: r.tiktokUrl ?? "",
    xUrl: r.xUrl ?? "",
    youtubeUrl: r.youtubeUrl ?? "",
    googleMapsUrl: r.googleMapsUrl ?? "",
    googleReviewsUrl: r.googleReviewsUrl ?? "",
    kdvNotice: r.kdvNotice ?? "",
    kdvNoticeEn: r.kdvNoticeEn ?? "",
    kdvNoticeAr: r.kdvNoticeAr ?? "",
    kdvNoticeRu: r.kdvNoticeRu ?? "",
    kdvNoticeDe: r.kdvNoticeDe ?? "", kdvNoticeFr: r.kdvNoticeFr ?? "", kdvNoticeEs: r.kdvNoticeEs ?? "",
    kdvNoticeIt: r.kdvNoticeIt ?? "", kdvNoticePl: r.kdvNoticePl ?? "", kdvNoticeZh: r.kdvNoticeZh ?? "",
    allergenNotice: r.allergenNotice ?? "",
    allergenNoticeEn: r.allergenNoticeEn ?? "",
    allergenNoticeAr: r.allergenNoticeAr ?? "",
    allergenNoticeRu: r.allergenNoticeRu ?? "",
    allergenNoticeDe: r.allergenNoticeDe ?? "", allergenNoticeFr: r.allergenNoticeFr ?? "", allergenNoticeEs: r.allergenNoticeEs ?? "",
    allergenNoticeIt: r.allergenNoticeIt ?? "", allergenNoticePl: r.allergenNoticePl ?? "", allergenNoticeZh: r.allergenNoticeZh ?? "",
    nutritionNotice: r.nutritionNotice ?? "",
    nutritionNoticeEn: r.nutritionNoticeEn ?? "",
    nutritionNoticeAr: r.nutritionNoticeAr ?? "",
    nutritionNoticeRu: r.nutritionNoticeRu ?? "",
    nutritionNoticeDe: r.nutritionNoticeDe ?? "", nutritionNoticeFr: r.nutritionNoticeFr ?? "", nutritionNoticeEs: r.nutritionNoticeEs ?? "",
    nutritionNoticeIt: r.nutritionNoticeIt ?? "", nutritionNoticePl: r.nutritionNoticePl ?? "", nutritionNoticeZh: r.nutritionNoticeZh ?? "",
    footerDescription: r.footerDescription ?? "",
    footerDescriptionEn: r.footerDescriptionEn ?? "",
    footerDescriptionAr: r.footerDescriptionAr ?? "",
    footerDescriptionRu: r.footerDescriptionRu ?? "",
    footerDescriptionDe: r.footerDescriptionDe ?? "", footerDescriptionFr: r.footerDescriptionFr ?? "", footerDescriptionEs: r.footerDescriptionEs ?? "",
    footerDescriptionIt: r.footerDescriptionIt ?? "", footerDescriptionPl: r.footerDescriptionPl ?? "", footerDescriptionZh: r.footerDescriptionZh ?? "",
    footerCopyright: r.footerCopyright ?? "",
    footerVisibility: normalizeFooterVisibility(r.footerVisibility),
    lastPriceChangeAt: r.lastPriceChangeAt?.toISOString().slice(0, 10) ?? "",
    attributionText: r.attributionText ?? "",
    attributionUrl: r.attributionUrl ?? "",
    themeAccent: r.themeAccent ?? "",
    themePrimary: r.themePrimary ?? "",
    themeSecondary: r.themeSecondary ?? "",
    themeBackground: r.themeBackground ?? "",
    themeBorder: r.themeBorder ?? "",
    themeText: r.themeText ?? "",
  };
}
